### ISSUE TITLE
Time, Date and Datetime doesn't exist in module datetime

### ISSUE THREAD

**Issue by edigiacomo** [cackharot/suds-py3#7]
I think the problem is the [`import datetime as dt` in `uds/xsd/sxbuiltin.py`](https://github.com/cackharot/suds-py3/blob/master/suds/xsd/sxbuiltin.py#L25): the objects `Date`, `Time`, `Datetime` are not in this module (but I found them in `suds.sax.date`).

I found the issue loading this WSDL: http://dati.meteotrentino.it/service.asmx?WSDL

**Comment by cackharot** [comment]
Fixed. Let me know if it works for you.

**Comment by victorjabur** [comment]
This error is not fixed yet.

At line Number 156 of the file "uds/xsd/sxbuiltin.py" which is "return str(dt.Date(value))"

import datetime as dt

The dt object doesn't have the Date method.

If you run a simple Python Script like as follow:

import datetime as dt
dt.Date(None)

You will see this error:
AttributeError: module 'datetime' has no attribute 'Date'

That's it.

Could you fix this piece of code ?

Thank you.
Victor

**Comment by victorjabur** [comment]
I've just fixed the function and now it is working. I will try to submit a Pull Request:

`class XDate(XBuiltin):
    """
    Represents an (xsd) xs:date builtin type.
    """

    def translate(self, value, topython=True):
        if topython:
            if isinstance(value, basestring) and len(value):
                return dt.datetime.strptime(value, '%Y-%m-%d').date()
                #return dt.Date(value).value
            else:
                return None
        else:
            if isinstance(value, dt.date):
                return '{:%Y-%m-%d}'.format(value)
                #return str(dt.Date(value))
            else:
                return value`

**Comment by rud-bookbites** [comment]
Can be safely closed after #22 and #23, right?

**Comment by cackharot** [comment]
Closing this. Reopen if issue still persists.
Thanks.
